blog/urls.py
# importing django routing libraries 
from . import views 
from django.urls import path, include 
from .views import *
  
urlpatterns = [ 

    path('', views.bloglist.as_view(), name='blogs'),
    path('create-blog', views.create_blog, name='create_blog'),   
    path('edit', views.editbloglist.as_view(), name='edit'),   
    path('edit/edit/<slug:slug>', views.blogEditView.as_view(), name='edit_blog'),  
    path('edit/delete/<slug:slug>', views.blogDeleteView.as_view(), name='deleteblog'),
    path('edit/<blog>/create-post', views.create_Post, name='create_post'),  
    path('edit/<blog>/', views.postseditlist.as_view(), name='postseditlist'),  
    path('edit/<blog>/delete/<slug:slug>', views.postDeleteView.as_view(), name='deletepost'), 
    path('edit/<blog>/<slug:slug>', views.postEditView.as_view(), name='editpost'),   
    path('<blog>/', views.postslist.as_view(), name='posts'), 
    path('<blog>/post/<slug:slug>', views.postdetail.as_view(), name='post_detail'),
    path('<blog>/post/<post>/delete/<pk>', views.deletecommentView.as_view(), name='deletecom'),
    path('<blog>/post/<slug:slug>/upvote', views.upvote, name='upvote'),
] 

blogcms3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include("blog.urls")),

]

blog/models.py
from django.db import models

from django.contrib.auth.models import User 
  

STATUS = ( 
    (0,"Draft"), 
    (1,"Publish"), 
    (2, "Delete") 
) 
 
class Blog(models.Model): 
    
    title = models.CharField(max_length=200, unique=True) 
   
    slug = models.SlugField(max_length=200, unique=True) 

    author = models.ForeignKey(User, on_delete= models.CASCADE) 
 
    updated_on = models.DateTimeField(auto_now= True) 
    created_on = models.DateTimeField(auto_now_add=True) 
    look  =  models.TextField(default="""#container img { 
border-radius: 29px; 
width: 100%; 
height: 360px; 
opacity: 0.7; 
align-content: center; 
} 
#container img { 
opacity: 1.0; } 
a {text-align: center; text-decoration: none;}""") 
  
    # meta for the class 
    class Meta: 
        ordering = ['-created_on'] 
    # used while managing models from terminal 
    def __str__(self): 
        return self.title 
	 

class posts(models.Model): 
    
    title = models.CharField(max_length=200, unique=True) 
   
    slug = models.SlugField(max_length=200, unique=True) 

    author = models.ForeignKey(User, on_delete= models.CASCADE) 
    blog = models.ForeignKey(Blog, on_delete= models.CASCADE) 

    updated_on = models.DateTimeField(auto_now= True) 
    created_on = models.DateTimeField(auto_now_add=True) 

    content = models.TextField() 

    metades = models.CharField(max_length=300, default="new post") 

    status = models.IntegerField(choices=STATUS, default=0) 
  
    vote = models.IntegerField( default=0) 
    # meta for the class 
    class Meta: 
        ordering = ['-created_on'] 
    # used while managing models from terminal 
    def __str__(self): 
        return self.title 
		

	
class Comment(models.Model): 
    
    
    author = models.ForeignKey(User, on_delete= models.CASCADE) 
    post = models.ForeignKey(posts, on_delete= models.CASCADE) 

    updated_on = models.DateTimeField(auto_now= True) 
    created_on = models.DateTimeField(auto_now_add=True) 

    content = models.TextField() 

  
    # meta for the class 
    class Meta: 
        ordering = ['-created_on'] 
    # used while managing models from terminal 
    def __str__(self): 
        return self.content 
		

blog/forms.py
from django.forms import ModelForm
from .models import posts, Blog, Comment

class BlogForm(ModelForm):
    class Meta:
	    model=Blog
	    fields = ['title', 'slug','look' ]
		
class PostForm(ModelForm):
    class Meta:
	    model=posts
	    fields = ['title', 'slug','content','status']

class CommentForm(ModelForm):
    class Meta:
	    model=Comment
	    fields = ['content']

blog/views.py
# importing models and libraries 
from django.shortcuts import render 
from .models import posts, Blog, Comment
from .forms import BlogForm, CommentForm, PostForm
from django.views import generic 
from django.views.decorators.http import require_GET 
from django.http import HttpResponse 
from django.shortcuts import get_object_or_404
from django.http import  HttpResponseRedirect
from django.contrib.auth.mixins import UserPassesTestMixin
 
# class based views for posts 
class postslist(generic.ListView): 
    model = posts
    template_name = 'home.html'
    paginate_by = 4
    def get_queryset(self):
        self.blog = get_object_or_404(Blog, slug=self.kwargs['blog'])
        return posts.objects.filter(status=1).filter(blog=self.blog).order_by('-created_on')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.blog = get_object_or_404(Blog, slug=self.kwargs['blog'])
        context['Blog'] = self.blog
        return context
 
class blogDeleteView(generic.DeleteView): 
    model = Blog 
    template_name = "delete.html"
    success_url ="/"
	
class postseditlist(generic.ListView): 
    model = posts
    template_name = 'posts_edit.html'
    paginate_by = 4
    def get_queryset(self):
        self.blog = get_object_or_404(Blog, slug=self.kwargs['blog'])
        return posts.objects.filter(blog=self.blog).order_by('-created_on')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.blog = get_object_or_404(Blog, slug=self.kwargs['blog'])
        context['Blog'] = self.blog
        return context
		
class postDeleteView(UserPassesTestMixin,generic.DeleteView): 
    model = posts 
    template_name = "delete.html"
    success_url ="/"		
    def test_func(self):
        return self.request.user.is_superuser

class deletecommentView(UserPassesTestMixin, generic.DeleteView): 
    model = Comment
    template_name = "delete.html"
    success_url ="/"	
    def test_func(self):
        return self.request.user.is_superuser
	
class postEditView(UserPassesTestMixin, generic.UpdateView): 
    model = posts 
    template_name = "post_edit.html"
    fields = ['title', 'slug','content','status']
    success_url ="/"	
    def test_func(self):
        return self.request.user.is_superuser
	
class blogEditView(UserPassesTestMixin, generic.UpdateView): 
    model = Blog 
    template_name = "post_edit.html"
    fields = ['title', 'slug','look']
    success_url ="/"	
    def test_func(self):
        return self.request.user.is_superuser	
	
class bloglist( generic.ListView): 
    model = Blog
    template_name = 'blogs.html'
    paginate_by = 4
    queryset= Blog.objects.order_by('-created_on') 	

	
class editbloglist(UserPassesTestMixin, generic.ListView): 
    model = Blog
    template_name = 'blogs_edit.html'
    paginate_by = 4
    def get_queryset(self):
        return Blog.objects.order_by('-created_on')  	
    def test_func(self):
        return self.request.user.is_superuser
		
class postdetail( generic.DetailView): 
    model = posts 
    template_name = "post.html"
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        self.post = get_object_or_404(posts, slug=self.kwargs['slug'])
        context['comments'] = Comment.objects.filter(post=self.post).order_by('-created_on') 
        context['Blog'] = get_object_or_404(Blog, slug=self.post.blog)
        return context
		
    def post(self, request,**kwargs):
        self.post = get_object_or_404(posts, slug=self.kwargs['slug'])
        form = CommentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.post=self.post 
            obj.author=request.user
            obj.author_id=request.user.id
            obj.save()
        return HttpResponseRedirect(request.path_info)

		
def create_Post(request, blog):
    if request.method == 'POST':
        if request.user.is_superuser:
            form = PostForm(request.POST)
            if form.is_valid():    
                obj = form.save(commit=False)
                obj.blog=get_object_or_404(Blog, slug=blog)
                obj.author=request.user
                obj.author_id=request.user.id
                obj.save()
                return HttpResponseRedirect('/'+blog)
    else:
        form = PostForm()

    return render(request, 'edit_post.html', {'form': form})

def upvote(request, blog, slug):
    obj = posts.objects.get(slug = slug)
    obj.vote+=1
    obj.save()
    return HttpResponseRedirect('/'+blog+'/post/'+slug)

	
def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author=request.user
            obj.author_id=request.user.id
            obj.save()
            return HttpResponseRedirect('/')

    else:
        form = BlogForm()

    return render(request, 'blog.html', {'form': form})

blog/templates/base.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
  <!-- will be replaced with meta content -->
  {% block metatags %}{% endblock %} 
  <meta charset="UTF-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1" /> 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> 
  <style> 

</style> 
</head> 
<body><div id="bodydiv"><div id="nofooter"> 
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav"> 
    <div class="container-fluid"> 
      <div class="nav justify-content-end"> 
        <div class="d-inline"></div> 
		
		<span>  <a href="/" class="btn btn-outline-primary">Main </a></span>  
        </div></div> 
</nav> 
   <!-- will be replaced with post content -->
{% block content %} 
{% endblock content %} 
</div> 
<footer class="footer" id="foot"> 
<nav class="navbar navbar-expand-lg"> 

  </nav> 
    </div> 
</footer></div> 
</body> 
</html> 

blog/templates/blog.html
{% extends "base.html" %} 

{% block content %}
<form action="create-blog" method="post">
    <table>
	{% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
	</table>
</form>

{% endblock%}

blog/templates/blogs.html
{% extends "base.html" %} 
{% block metatags %} 

{% endblock %} 
{% block content %} 
<style type="text/css"> 
    body { 
       font-family:  'Raleway', sans-serif;} 
    .head_text { 
        color: white; 
    } 
.h1, h4 { 
font-family: 'Raleway', sans-serif; 
} 
#mainhome { 
text-align: center; } 
</style> 
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;"> 
    <div class="container"> 
      <p class="h1"> </p> 
                </div> 
				<span>  <a href="/" class="btn btn-outline-primary">Main </a></span>  
				{% if user.is_anonymous %}
 <span><a href="accounts/" class="btn btn-outline-primary">Log in</a></span> 
				       <span><a href="accounts/register/" class="btn btn-outline-primary">Register</a></span> 
{% else %}
				{% if user.is_superuser %}
    <span><a href="accounts/" class="btn btn-outline-primary">Menu</a></span> 
	{% endif %}
				       <span><a href="accounts/logout/" class="btn btn-outline-primary">Log Out</a></span> 
{% endif %}
				       
</header> 
<div class="container"> 
    <div class="row"> 
        <div class="col-md-8 mt-3 left"> 
            {% for blog in blog_list %} 
            <div class="shadow-none card mb-4" id="newsfeed"> 
                <div class="card-body"> 
                    <h3 class="card-title">{{ blog.title }}</h3> 
                    <p class="card-text text-muted h6"><span>{{ blog.author}}</span> | {{ blog.created_on}} </p> 
                    <span><a href="{% url 'posts' blog.slug  %}" class="btn btn-outline-primary">Read More →</a></span>
                </div> 
            </div> 
            {% endfor %} 
        </div> 
</div> 
</div> 
{% if is_paginated %} 
  <nav aria-label="Page navigation conatiner"></nav> 
  <ul class="pagination justify-content-center"> 
    {% if page_obj.has_previous %} 
    <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li> 
    {% endif %} 
    {% if page_obj.has_next %} 
    <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li> 
  
    {% endif %} 
  </ul> 
{% endif %} 
{%endblock%} 

blog/templates/blogs_edit.html
{% extends "base.html" %} 
{% block metatags %} 

{% endblock %} 
{% block content %} 
<style type="text/css"> 
    body { 
       font-family:  'Raleway', sans-serif;} 
    .head_text { 
        color: white; 
    } 
.h1, h4 { 
font-family: 'Raleway', sans-serif; 
} 
#mainhome { 
text-align: center; } 
</style> 
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;"> 
    <div class="container"> 
      <p class="h1"> </p> 
                </div> <span>  <a href="/" class="btn btn-outline-primary">Main </a></span> 
				       <span><a href="accounts/logout" class="btn btn-outline-primary">Log out</a></span> 
</header> 
<div class="container"> 
    <div class="row"> 
        <div class="col-md-8 mt-3 left"> 
            {% for blog in blog_list %} 
            <div class="shadow-none card mb-4" id="newsfeed"> 
                <div class="card-body"> 
                    <h3 class="card-title">{{ blog.title }}</h3> 
                    <p class="card-text text-muted h6"><span>{{ blog.author}}</span> | {{ blog.created_on}} </p> 
                    <span><a href="{% url 'postseditlist' blog.slug  %}" class="btn btn-outline-primary">Read More →</a></span>
                    <span><a href="{% url 'deleteblog' blog.slug  %}" class="btn btn-outline-primary">Delete →</a></span>
                </div> 
            </div> 
            {% endfor %} 
        </div> 
</div> 
</div> 
{% if is_paginated %} 
  <nav aria-label="Page navigation conatiner"></nav> 
  <ul class="pagination justify-content-center"> 
    {% if page_obj.has_previous %} 
    <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li> 
    {% endif %} 
    {% if page_obj.has_next %} 
    <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li> 
  
    {% endif %} 
  </ul> 
{% endif %} 
{%endblock%} 

blog/templates/comment_form.html
{% extends "base.html" %}

{% block header %}
    {{ comment_form.media }}
{% endblock %}

{% block content %}
{{ form.media }}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
{% endblock %}

blog/templates/delete.html
{% extends "base.html" %} 
{% block content %}

<span>  <a href="/" class="btn btn-outline-primary">Main </a></span> 
<form method="post">{% csrf_token %} 
    <p>Are you sure you want to delete "{{ object }}"?</p> 
    <input type="submit" value="Confirm"> 
</form> 
{% endblock %}

blog/templates/edit_post.html
{% extends "base.html" %} 

{% block content %}
<span>  <a href="/" class="btn btn-outline-primary">Main </a></span> 
<form action="create-post" method="post">
    {% csrf_token %}
	<table>
    {{ form.as_table }}
    <input type="submit" value="Submit">
	</table>
</form>

{% endblock%}

blog/templates/home.html
{% extends "base.html" %} 
{% block metatags %} 

{% endblock %} 
{% block content %} 
<style type="text/css"> 
  {{Blog.look}}
</style> 
<header class="jumbotron" > 
    <div class="container"> 
 
<span>  <a href="/" class="btn btn-outline-primary">Main </a></span>  

</header> 						
<div class="container"> 
    <div class="row"> 
        <div class="col-md-8 mt-3 left"> 
            {% for post in posts_list %} 
            <div class="shadow-none card mb-4" id="newsfeed"> 
                <div class="card-body"> 
                    <h3 class="card-title">{{ post.title }}</h3> 
                    <p class="card-text text-muted h6"><span>{{ post.author.first_name }} {{ post.author.last_name }}</span> | {{ post.created_on}} </p> 
                    <p class="card-text">{{post.metades }}</p> 
                    <span><a href="{% url 'post_detail' post.blog post.slug  %}" class="btn btn-outline-primary">Read More →</a></span> 
                </div> 
            </div> 
            {% endfor %} 
        </div> 
</div> 
</div> 
{% if is_paginated %} 
  <nav aria-label="Page navigation conatiner"></nav> 
  <ul class="pagination justify-content-center"> 
    {% if page_obj.has_previous %} 
    <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li> 
    {% endif %} 
    {% if page_obj.has_next %} 
    <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li> 
  
    {% endif %} 
  </ul> 
{% endif %} 
{%endblock%} 

blog/templates/post.html
{% extends 'base.html' %} 
{% block metatags %} 
<title>{{ object.title }}</title> 

{% endblock %} 
{% block content %} 
<style type="text/css"> 
{{Blog.look}}
</style> 
		<span>  <a href="/" class="btn btn-outline-primary">Main </a></span>  

<div class="container"> 
  <div class="row">   
<div class="col-md-6 left"> 
        <h1 class="card-title">{% block title %} {{ object.title }} {% endblock title %}</h1> 
        <p class=" text-muted">{{ object.author }}|{{ object.created_on }}</p> 
        <p class="card-text">{{ object.content | safe }}</p> 
        <p class="card-text">{{ object.vote }}</p> 
		<a href={% url 'upvote' object.blog object.slug  %} class="btn btn-outline-primary">Upvote </a>
      </div> 
       </div>
            {% for comment in comments %}
                <div class=" col-md-12 comment">
                    <div class="date">{{ comment.created_date }}</div>
                    <strong>{{ comment.author }}</strong>
                    <p>{{ comment.content|linebreaks }}</p>	
					
					{% if user.is_superuser %}
    <span><a href={% url 'deletecom' object.blog object.slug comment.pk %} class="btn btn-outline-primary">Delete</a></span> 
	{% endif %}
                </div>
            {% empty %}
                <p>No comments here yet :(</p>
            {% endfor %}	
	{% if user.is_authenticated %}			
       <form method="POST">
  {% csrf_token %}
    {{form}}
    <input type="submit" name="comment" class="btn btn-warning">
  
</form>    
{% endif %}
	   </div> 
	   
	   
{% endblock content %} 

blog/templates/post_edit.html
{% extends "base.html" %} 

{% block content %}
<form method="post">
<table>
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Save">
</table
</form>

{% endblock%}

blog/templates/posts_edit.html
{% extends "base.html" %} 
{% block metatags %} 

{% endblock %} 
{% block content %} 
<style type="text/css"> 
    body { 
       font-family:  'Raleway', sans-serif;} 
    .head_text { 
        color: white; 
    } 
.h1, h4 { 
font-family: 'Raleway', sans-serif; 
} 
#mainhome { 
text-align: center; } 
</style> 
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;"> 
    <div class="container"> 
      <p class="h1"> </p> 
                </div> 
		<span>  <a href="/" class="btn btn-outline-primary">Main </a></span> 		
        <span><a href="create-post" class="btn btn-outline-primary">Add Post</a></span>
		<span><a href="{% url 'edit_blog' Blog.slug %}" class="btn btn-outline-primary">Edit Blog</a></span>  
</header> 
<div class="container"> 
    <div class="row"> 
        <div class="col-md-8 mt-3 left"> 
            {% for post in posts_list %} 
            <div class="shadow-none card mb-4" id="newsfeed"> 
                <div class="card-body"> 
                    <h3 class="card-title">{{ post.title }}</h3> 
                    <p class="card-text text-muted h6"><span>{{ post.author.first_name }} {{ post.author.last_name }}</span> | {{ post.created_on}} </p> 
                    <p class="card-text">{{post.metades }}</p> 
                    <span><a href="{% url 'editpost' post.blog post.slug  %}" class="btn btn-outline-primary">Edit →</a></span> 
                    <span><a href="{% url 'deletepost' post.blog post.slug  %}" class="btn btn-outline-primary">Delete →</a></span> 
                </div> 
            </div> 
            {% endfor %} 
        </div> 
</div> 
</div> 
{% if is_paginated %} 
  <nav aria-label="Page navigation conatiner"></nav> 
  <ul class="pagination justify-content-center"> 
    {% if page_obj.has_previous %} 
    <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li> 
    {% endif %} 
    {% if page_obj.has_next %} 
    <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li> 
  
    {% endif %} 
  </ul> 
{% endif %} 
{%endblock%} 